name: 'Docker Stale Package Remover'
description: 'Limit the amount of images in your github registry by keeping only the latest X images'
author: 'Jonas Dellinger'
inputs:
  token: # change this
    required: true
    description: 'A github auth token.'
  packages:
    required: true
    description: 'A comma seperated list of package names.'
  keep:
    required: true
    description: 'A number specifying how many images should be kept.'
runs:
  using: 'node12'
  main: 'dist/index.js'
